# Generated by Django 5.1.2 on 2024-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('assertiva1', models.CharField(max_length=200)),
                ('assertiva2', models.CharField(max_length=200)),
                ('assertiva3', models.CharField(max_length=200)),
                ('assertiva4', models.CharField(max_length=200)),
                ('resposta', models.IntegerField()),
            ],
        ),
    ]
