# Generated by Django 5.1.2 on 2024-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simuladosingles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="assertiva1",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="assertiva2",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="assertiva3",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="assertiva4",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="pergunta",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="resposta",
            field=models.CharField(max_length=500),
        ),
    ]
