# Generated by Django 5.1.2 on 2024-10-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simuladosingles", "0003_fillinblank"),
    ]

    operations = [
        migrations.CreateModel(
            name="FillInBlank_by_topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=500)),
                ("pergunta", models.CharField(max_length=5000)),
                ("resposta", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="Question_by_topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=500)),
                ("pergunta", models.CharField(max_length=500)),
                ("assertiva1", models.CharField(max_length=500)),
                ("assertiva2", models.CharField(max_length=500)),
                ("assertiva3", models.CharField(max_length=500)),
                ("assertiva4", models.CharField(max_length=500)),
                ("resposta", models.CharField(max_length=500)),
            ],
        ),
    ]
